sudo: false
language: node_js
node_js: stable
after_success:
  - |

        $(npm bin)/set-up-ssh --key "$encrypted_567c1b6fa013_key" \
                             --iv "$encrypted_567c1b6fa013_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commands "npm run build" \
                                 --commit-message "Update website [skip ci]" \
                                 --directory "website/public" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"